### ISSUE TITLE
Error: Cannot find module '@nighttrax/foo'

### ISSUE THREAD

**Issue by MichaelGatesDev** [NiGhTTraX/lerna-ts#2]
I tried installing ts-node-dev to run the index file to see if it would throw this error, and indeed it did. For some reason, I just can not get monorepos to work for me. Even if VSCode detects symbols correctly, node can not resolve the modules at runtime. 

```
[sparta@sparta-pc lerna-ts-master]$ yarn tsnd packages/bar/src/index.ts 
yarn run v1.19.0
$ /data/downloads/lerna-ts-master/node_modules/.bin/tsnd packages/bar/src/index.ts
Using ts-node version 8.6.2, typescript version 3.4.5
Error: Cannot find module '@nighttrax/foo'
Require stack:
- /data/downloads/lerna-ts-master/packages/bar/src/index.ts
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/data/downloads/lerna-ts-master/packages/bar/src/index.ts:1:1)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Module._compile (/data/downloads/lerna-ts-master/node_modules/source-map-support/source-map-support.js:541:25)
    at Module.m._compile (/tmp/ts-node-dev-hook-048440305208922174.js:57:25)
    at Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at require.extensions.<computed> (/tmp/ts-node-dev-hook-048440305208922174.js:59:14)
[ERROR] 19:28:04 Error: Cannot find module '@nighttrax/foo'
Require stack:
- /data/downloads/lerna-ts-master/packages/bar/src/index.ts
```

**Comment by NiGhTTraX** [comment]
Hey @MichaelGatesDev, you need to use the [tsconfig-paths](https://github.com/dividab/tsconfig-paths) package to support the path aliases in tsnode. This is because the path aliases are only used at compile time by the TS compiler and are left untouched in the transpiled code.

**Comment by MichaelGatesDev** [comment]
@NiGhTTraX Thanks for that information. I've been going crazy trying to figure out why it doesn't work out-of-the-box.
